[FEAT] Expand code Link
RocketChat/Apps.Github22 pull request #116
Opened 2023-06-19 16:39 UTC by VipinDevelops

## Issue(s) 
Closes #26 

## Acceptance Criteria fulfillment

This pull request  focuses on fulfilling the acceptance criteria related to expanding code links .

The changes introduced in this PR involve the following steps:

- The `checkPreMessageSentExtend` function first verifies whether the received message contains a GitHub link.
- The `executePreMessageSentExtend` function then checks if the identified link is a code link. 
- Finally, the` handleCodeLink` function is responsible for adding an attachment to the message, thereby expanding the code link.
## Proposed changes (including videos or screenshots)

![image](https://github.com/RocketChat/Apps.Github22/assets/99081689/ca8e99f7-2d61-4652-96f8-405fc8c2668a)

2023-06-27 20:05 UTC, samad-yar-khan requested changes
@VipinDevelops  Thanks for the PR. This is an amazing contribution. Please go through the requested changes.

2023-06-28 09:26 UTC, VipinDevelops commented on github/GithubApp.ts
> +export class GithubApp extends App implements IPreMessageSentExtend {
Yeah I tried searching for something else but implementing the `IPreMessageSentExtend `interface in the `GithubApp` class is the remains approach,  We do not have any other way  for PreMessageSent

2023-06-28 09:27 UTC, VipinDevelops commented on github/GithubApp.ts
> +        }
Sure Ill update the name's

2023-06-28 11:43 UTC, VipinDevelops commented on github/GithubApp.ts
> +
sure I Fixed This

2023-06-28 11:44 UTC, VipinDevelops commented on github/handlers/HandleLinks.ts
> +    url = url.replace("github.com", "raw.githubusercontent.com");
Sure I made enums for this

2023-06-28 11:47 UTC, VipinDevelops commented on github/handlers/HandleLinks.ts
> +
So I should introduce and implement the Test for this using JEST or something ?

2023-07-06 03:32 UTC, VipinDevelops commented
Hello @samad-yar-khan  Sir i made all the requested changes in the PR

2023-07-09 14:54 UTC, samad-yar-khan requested changes

2023-07-09 14:54 UTC, samad-yar-khan commented on github/handlers/GitHubCodeSegmentHandler.ts
> +
Missing some indentation
```
if (lineRangeMatch) {
    return extractCodeSnippetByLineRange(content, lineRangeMatch);
}
```

2023-07-09 16:48 UTC, samad-yar-khan reviewed
This is an amazing contribution to our project ! Thanks a lot @VipinDevelops

2023-07-09 16:48 UTC, samad-yar-khan approved these changes
LGTM !

2023-07-09 16:48 UTC, merged